### ISSUE TITLE
Instrument search broken

### ISSUE THREAD

**Issue by tjader** [Qluxzz/avanza#113]
It looks like the old _mobile has removed its search capability, so any of the `client.search_for*`functions now return a 404 error.
```python
>>> client.search_for_instrument(InstrumentType.STOCK, 'SAAB')
...
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.avanza.se/_mobile/market/search/STOCK?query=SAAB&limit=10
```

**Comment by tjader** [comment]
I pushed a PR for this (please feel free to reject if the issue is purely on my side).

**Comment by sege** [comment]
Any idea on how to get the ticker when searching now? Doesn't seem to be in the search result what I can see.

Any tips?

**Comment by sege** [comment]
> Any idea on how to get the ticker when searching now? Doesn't seem to be in the search result what I can see.
> 
> Any tips?

Never mind, between parenteses.
