### ISSUE TITLE
Subscription ends with error

### ISSUE THREAD

**Issue by highviolet** [Qluxzz/avanza#15]
First of all, thank you for a great package.

I have a problem with subscriptions to channels that ends with an error.
It occurs after the subscription has been running for roughly three hours.
An ideas on how to avoid it?

`Task exception was never retrieved
future: <Task finished name='Task-2' coro=<AvanzaSocket.__create_socket() done, defined at .../python3.9/site-packages/avanza/avanza_socket.py:45> exception=TypeError("'>=' not supported between instances of 'NoneType' and 'int'")>
Traceback (most recent call last):
  File ".../python3.9/site-packages/avanza/avanza_socket.py", line 51, in __create_socket
    await self.__socket_message_handler()
  File ".../python3.9/site-packages/avanza/avanza_socket.py", line 188, in __socket_message_handler
    await action(message)
  File ".../python3.9/site-packages/avanza/avanza_socket.py", line 129, in __connect
    not advice or (reconnect and interval >= 0)
TypeError: '>=' not supported between instances of 'NoneType' and 'int'`

**Comment by highviolet** [comment]
Hi,

I made some investigations into this.

The lines:
`connect_successful = successful and (
            not advice or (reconnect and interval >= 0)
        )
`
Should likely be changed to:
`connect_successful = successful and (
            not advice or (reconnect != 'none' and interval >= 0)
        )
`

Compare with https://github.com/fhqvst/avanza/blob/ca5e9053ff33e7ab1a163a19f2f4e19395cff479/lib/index.js#L299

However, after that change, I encounter a new error. When the subscription has been running for approx. 4 hours, I now get "402 :: Unkown client".

**Comment by Qluxzz** [comment]
Your problem after four hours might be because of this?
You can change the time at Profil -> Sajtinställningar -> Automatisk utloggning.
![image](https://user-images.githubusercontent.com/3757388/103183471-02e77080-48b3-11eb-8e8e-000bb9222e82.png)

**Comment by Qluxzz** [comment]
> The lines:
> `connect_successful = successful and ( not advice or (reconnect and interval >= 0) ) `
> Should likely be changed to:
> `connect_successful = successful and ( not advice or (reconnect != 'none' and interval >= 0) ) `

Yeah, that sure seems like it. I will create a fix for it.

Thanks for investigation the issue!
