### ISSUE TITLE
Add method to get transactions

### ISSUE THREAD

**Issue by highviolet** [Qluxzz/avanza#18]
Hi!

I propose adding a new method to get transactions. (Inspired by https://github.com/fhqvst/avanza/blob/ca5e9053ff33e7ab1a163a19f2f4e19395cff479/lib/index.js#L540)

I was unable to push a new branch to the repo, so I am attaching the python file here instesead.

[avanza.py.txt](https://github.com/Qluxzz/avanza/files/5792528/avanza.py.txt)

**Comment by Qluxzz** [comment]
Here's a guide on how to create a pull request and contributing to this project: https://git-scm.com/book/en/v2/GitHub-Contributing-to-a-Project

It will make it much easier for me to compare the code and after a finished pull request you will be added as a contributor to this project, which you are definitely entitled to by helping me out improving the project!

**Comment by highviolet** [comment]
Thanks!
I'll read that and come back with a proper pull request.
