### ISSUE TITLE
Help needed 

### ISSUE THREAD

**Issue by GentoGaming** [Qluxzz/avanza#22]
I dont know why i am getting this error , can anyone tell me how to fix ? 
    self._authentication_session = response_body['authenticationSession']
KeyError: 'authenticationSession'

**Comment by Qluxzz** [comment]
Have you followed the guide in the [README](/Qluxzz/avanza/blob/master/README.md)  and tried out the first example snippet? Do you still get the same error then?

**Comment by GentoGaming** [comment]
This : import hashlib
import pyotp
totp = pyotp.TOTP('MY_TOTP_SECRET', digest=hashlib.sha1)
print(totp.now())
Worked and gave me the code

**Comment by GentoGaming** [comment]
from avanza import Avanza
avanza = Avanza({
    'username': 'MY_USERNAME',
    'password': 'MY_PASSWORD',
    'totpSecret': 'MY_TOTP_SECRET'
})

overview = avanza.get_overview()

This didnt work . 
self._authentication_session = response_body['authenticationSession']
KeyError: 'authenticationSession'

**Comment by Qluxzz** [comment]
And logging into [Avanza](https://www.avanza.se) directly on their website using your username and password and totp-code works?
![image](https://user-images.githubusercontent.com/3757388/108628375-d6874500-745a-11eb-83ac-0010604d968c.png)

**Comment by vonDassendorf** [comment]
Just to clarify you should give the Avanza class the secret (that you get from avanza when enabling 2fa) that is used to generate the totp code and not the code generated by pyotp.
