### ISSUE TITLE
Adding the library to GST

### ISSUE THREAD

**Issue by Deel18** [Qluxzz/avanza#37]
Hi,

I'm currently looking into some possible solutions for integrating Avanza as a broker into the [GamestonkTerminal](https://github.com/GamestonkTerminal/GamestonkTerminal) and stumbled onto your library.

I would like to make use of your library and add it to the terminal, but I wanted to just check with you if you are planning on maintaining it for the forseeable future? And of course, would this be okay with you? Seeing as you mention that it is mainly experimental and should not be actually used...

**Comment by Qluxzz** [comment]
I only maintain this library in terms of reviewing and merging Pull Requests, and occasionally responding to issues nowadays. Would any major changes happen to the underlying API I don't give any guarantees that I will have time to rewrite it.

Some things that would make this library useless is if Avanza would remove the possibility to login using username and password, and only rely on [BankID](https://www.bankid.com/).

So use at your own risk.
