### ISSUE TITLE
405 Client Error when placing order

### ISSUE THREAD

**Issue by RagnarHagberg** [Qluxzz/avanza#47]
Placing an order does gives an error.
Error:
requests.exceptions.HTTPError: 405 Client Error: Method Not Allowed for url: https://www.avanza.se/_api/order

URI: | /_api/order
Status: 405
Message: Request method 'GET' not supported

with this data:
           account_id="XXXXXXX",
           order_book_id=290011
           order_type=OrderType.SELL,
           price=79.6,
           valid_until=2022-02-17
           volume=1.0

**Comment by RagnarHagberg** [comment]
The example to buy does not work either.
https://pypi.org/project/avanza-api/.

**Comment by RagnarHagberg** [comment]
I got the same error but I wrote what was in the link. Avanza might have changed their API which would lead to this not working.

**Comment by AmirEghbali** [comment]
It is possible to read prices etc but order placement does not work apparently today.

**Comment by Alexey-Klechikov** [comment]
Hej guys. The fix for the issue is to replace an endpoint for order creation in the constants.py.
Row 96: "ORDER_PLACE_PATH = '/_cqbe/trading/order/new'" 

Could the author make a fix?

**Comment by tux2000** [comment]
Fixed in my branch, see pull request...

**Comment by Alexey-Klechikov** [comment]
Addition to my last comment to fix the order type - update avanza.py, 
Row 1528: " 'side': order_type.value," -

**Comment by Qluxzz** [comment]
I have published a new version, 3.0.1 which includes these changes.
