### ISSUE TITLE
402::Unknown client and 403::Handshake denied

### ISSUE THREAD

**Issue by SleepyStudent** [Qluxzz/avanza#52]
Im getting this errors after exactly 4 hours of streaming data.

402::Unknown client
402::Unknown client
403::Handshake denied
402::Unknown client
402::Unknown client

Running:
async def subscribe_to_channel(avanza: Avanza):
    await avanza.subscribe_to_id

in an:
    asyncio.get_event_loop().run_forever()

Any ideas of where the problem might be?

**Comment by jonasoreland** [comment]
I had that problem too.
I fixed it by modifying the "auto logout" timer (or something like that) on the avanza website.
