### ISSUE TITLE
Order placing servlet URI is 404

### ISSUE THREAD

**Issue by dichai1983** [Qluxzz/avanza#67]
/_cqbe/trading/order/new is 404

Does anyone know what it is now?

Thanks

**Comment by svennystrom** [comment]
+1

**Comment by dichai1983** [comment]
What should we do with it? Should we inspect the web app to see what is the post request & response of the order placing action?

Thanks

**Comment by dichai1983** [comment]
![P_20221124_112510.jpg](https://user-images.githubusercontent.com/6367237/203760722-539c3809-7a3f-4ae7-bb0a-6e8ffe562dcb.jpg)

**Comment by jfla011** [comment]
found it!
`    ORDER_PLACE_PATH = '/_api/trading-critical/rest/order/new'
`

**Comment by jfla011** [comment]
haha, looks like you just beat me to it :D

**Comment by Qluxzz** [comment]
#69 has been merged and version 4.0.1 has been released with these changes

**Comment by svennystrom** [comment]
Note that there is a corresponding URL for delete_order: '/_api/trading-critical/rest/order/delete'

I haven't verified if the previous URL is broken though, so could be that an updated is not required.

**Comment by anirbankrishna** [comment]
dichai1983, how did you figure out the new url? What kind of tool did you use?

**Comment by dichai1983** [comment]
> dichai1983, how did you figure out the new url? What kind of tool did you use?

It's chrome network tools applied on the web app.

**Comment by anirbankrishna** [comment]
dicahi1983, have you used the getorder method/function? I got a 400 error from that method. Could it be that the order was already executed when I made the query?

**Comment by dichai1983** [comment]
> dicahi1983, have you used the getorder method/function? I got a 400 error from that method. Could it be that the order was already executed when I made the query?

No, I haven't used the get order method.

**Comment by anirbankrishna** [comment]
> > dicahi1983, have you used the getorder method/function? I got a 400 error from that method. Could it be that the order was already executed when I made the query?
> 
> No, I haven't used the get order method.

Thanks dichai1983.
