### ISSUE TITLE
get_chart_data gives 404 URL not found

### ISSUE THREAD

**Issue by Madbull25** [Qluxzz/avanza#68]
seems the url for get_chart_data isnt correct, was working yesterday, today i keep getting 404 error, that the url doesnt exist

Anyone else having this problem?

**Comment by Madbull25** [comment]
wrapper is using this path, and its still working
/ab/component/highstockchart/getchart/orderbook

**Comment by vasba** [comment]
@Madbull25  
The new path seems to have the same issue using modified constant
CHARTDATA_PATH = '/ab/component/highstockchart/getchart/orderbook/{}'
Example url:
 https://www.avanza.se/ab/component/highstockchart/getchart/orderbook/19002?timePeriod=one_week&resolution=ten_minutes

**Comment by Madbull25** [comment]
https://www.avanza.se/_api/price-chart/stock/220127?timePeriod=five_years

IS WORKING
timeperiods are today, one week, one_month, three_months, this_year, one_year, three_years, five_years, infinity

resolution are for:
today : minute", "two_minutes", "five_minutes", "ten_minutes", "thirty_minutes", "hour", "day
one week:  "ten_minutes", "thirty_minutes", "hour", "day"
one_month: "hour", "day", "week" 
three_month: "day", "week", "month
this_year: day", "week", "month
one_year: "day", "week", "month", "quarter"
three_years: day", "week", "month", "quarter"
five_years: "day", "week", "month", "quarter"
infinity: "week", "month", "quarter" 

so the paths on constant are wrong, same with the timeperiods, cant find five_years_rolling anywhere
