### ISSUE TITLE
INSTRUMENT_PATH gives error 404

### ISSUE THREAD

**Issue by tux2000** [Qluxzz/avanza#70]
Access to https://www.avanza.se/_mobile/market/fund/56127 comes back as status 404. 
On the website the fund is at https://www.avanza.se/fonder/om-fonden.html/56127/simplicity-likviditet-a not sure what the new corresponding API url might be

https://github.com/Qluxzz/avanza/blob/82856b6eb73b26682a1286fd266273e0405fbfef/avanza/constants.py#L99

**Comment by tux2000** [comment]
Now I get a 404 also for certificates, e.g. https://www.avanza.se/_mobile/market/certificate/1343528

Not sure if https://www.avanza.se/_api/market-guide/certificate/1343528 would be a suitable replacement url.

**Comment by AmirEghbali** [comment]
I think this can be closed

**Comment by tux2000** [comment]
Indeed, can be closed, fixed in #74
