### ISSUE TITLE
get_positions() no working

### ISSUE THREAD

**Issue by Unt3r** [Qluxzz/avanza#91]
avanza.get_positions()

requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.avanza.se/_mobile/account/positions

**Comment by jonasoreland** [comment]
could this be related ?
https://github.com/fhqvst/avanza/issues/99

**Comment by Unt3r** [comment]
Yes, the paths have changed.

ACCOUNTS_POSITIONS_PATH = '/_api/position-data/positions'  <- still works
POSITIONS_PATH = '/_mobile/account/positions' <- don't work

ACCOUNT_OVERVIEW_PATH = '/_mobile/account/{}/overview' <- don't work
OVERVIEW_PATH = '/_mobile/account/overview' <- don't work

an overview seems to be:
/_api/account-performance/overview/total-values 
but with different output.

**Comment by Qluxzz** [comment]
Has been superseded by the get_accounts_positions method https://qluxzz.github.io/avanza/avanza/avanza.html#Avanza.get_accounts_positions
